;------------------------------------------------------------------------------
; Менеджер сервисов Windows
;
; Файл:      subserventdlg.inc
; Описание:  диалоговые окна прав доступа и соединения с удаленным компьютером
; Автор:     Иванцов Илья Сергеевич, YormLokison@yandex.ru
;------------------------------------------------------------------------------

SCMAccessDialogFunc proto hWnd:HWND, uMsg:UINT, wParam:WPARAM, lParam:LPARAM
ServAccessDialogFunc proto hWnd:HWND, uMsg:UINT, wParam:WPARAM, lParam:LPARAM
ConnectToDialogFunc proto hWnd:HWND, uMsg:UINT, wParam:WPARAM, lParam:LPARAM
